[alembic]
script_location = alembic
sqlalchemy.url = postgresql+asyncpg://hubspot:hubspot@localhost:5432/hubspot

[loggers]
keys = root, sqlalchemyl

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemyl]
level = INFO
handlers = console
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
